<script setup lang="ts">
import { Head, router } from "@inertiajs/vue3";
import CourierLayout from "@/Layouts/CourierLayout.vue";
import Pagination from "@/Components/UI/Pagination.vue";
interface Row { id: number; amount: string; paid_at?: string; invoice: { invoice_number: string; invoice_date: string; billing_name: string; billing_company?: string } }
interface Page { data: Row[]; links: { url: string | null; label: string; active: boolean }[] }
const props = defineProps<{ rows: Page; summary: { paid: number; unpaid: number }; filters: { status: string } }>();
const money = (v: unknown) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(Number(v));
const filter = (status: string) => router.get(route("courier.earnings.index"), { status }, { preserveState: true, replace: true });
</script>
<template><Head title="Ongkir Kurir"/><CourierLayout><div class="mb-5"><h1 class="text-2xl font-bold">Ongkir Saya</h1><p class="mt-1 text-sm text-slate-500">Rincian ongkir yang sudah dan belum dibayarkan.</p></div><div class="mb-5 grid grid-cols-2 gap-3"><div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p class="text-xs text-emerald-700">Sudah Dibayar</p><strong class="mt-1 block text-xl text-emerald-700">{{money(summary.paid)}}</strong></div><div class="rounded-xl border border-amber-200 bg-amber-50 p-4"><p class="text-xs text-amber-700">Belum Dibayar</p><strong class="mt-1 block text-xl text-amber-700">{{money(summary.unpaid)}}</strong></div></div><div class="mb-4 flex gap-2"><button v-for="item in [{v:'',l:'Semua'},{v:'paid',l:'Dibayar'},{v:'unpaid',l:'Belum Dibayar'}]" :key="item.v" class="rounded-lg border px-3 py-2 text-xs font-semibold" :class="filters.status===item.v?'border-sky-500 bg-sky-50 text-sky-700':'border-slate-200 bg-white text-slate-600'" @click="filter(item.v)">{{item.l}}</button></div><section class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div v-if="!rows.data.length" class="p-10 text-center text-sm text-slate-500">Belum ada data ongkir.</div><article v-for="row in rows.data" :key="row.id" class="flex items-center justify-between border-b border-slate-100 p-4"><div><p class="font-semibold text-sky-700">{{row.invoice.invoice_number}}</p><p class="mt-1 text-xs text-slate-500">{{row.invoice.billing_company||row.invoice.billing_name}} · {{new Date(row.invoice.invoice_date).toLocaleDateString('id-ID')}}</p></div><div class="text-right"><strong>{{money(row.amount)}}</strong><p class="mt-1 text-xs font-semibold" :class="row.paid_at?'text-emerald-600':'text-amber-600'">{{row.paid_at?'Sudah Dibayar':'Belum Dibayar'}}</p></div></article><div class="p-4"><Pagination :links="rows.links"/></div></section></CourierLayout></template>
