<script setup lang="ts">
import { Head } from "@inertiajs/vue3";
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.vue";
import ReportFilters from "@/Components/Reports/ReportFilters.vue";
import ReportPageHeader from "@/Components/Reports/ReportPageHeader.vue";
import ReportStatCard from "@/Components/Reports/ReportStatCard.vue";
import Pagination from "@/Components/UI/Pagination.vue";
interface Row{id:number;transaction_number:string;transaction_date:string;type:string;category:string;description:string;payment_method:string;amount:string;reference_number?:string}
interface PageData{data:Row[];links:{url:string|null;label:string;active:boolean}[];from:number|null;to:number|null;total:number}
interface Summary{transaction_count:number;incoming_total:string;outgoing_total:string;balance:string}
defineProps<{summary:Summary;rows:PageData;filters:Record<string,string>}>();
const money=(v:string|number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v));
const date=(v:string)=>new Date(`${v.slice(0,10)}T00:00:00`).toLocaleDateString("id-ID");
</script>
<template><Head title="Laporan Kas"/><AuthenticatedLayout><template #breadcrumb>Laporan / Kas</template><ReportPageHeader title="Laporan Kas" description="Arus Kas Masuk dan Kas Keluar dalam satu laporan."/><ReportFilters route-name="reports.cash" :filters="filters" search-placeholder="Cari nomor transaksi, kategori, atau referensi..." show-cash-type/><div class="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ReportStatCard label="Jumlah Transaksi" :value="`${summary.transaction_count} transaksi`" icon="cash"/><ReportStatCard label="Kas Masuk" :value="money(summary.incoming_total)" tone="emerald" icon="cash"/><ReportStatCard label="Kas Keluar" :value="money(summary.outgoing_total)" tone="amber" icon="cash"/><ReportStatCard label="Saldo Kas" :value="money(summary.balance)" tone="violet" icon="margin"/></div><section class="panel"><div class="table-wrap"><table class="data-table min-w-[900px]"><thead><tr><th>Tanggal</th><th>Nomor Transaksi</th><th>Jenis</th><th>Kategori</th><th>Keterangan</th><th>Metode</th><th class="text-right">Nominal</th></tr></thead><tbody><tr v-for="row in rows.data" :key="row.id"><td>{{date(row.transaction_date)}}</td><td class="font-semibold text-sky-600">{{row.transaction_number}}</td><td><span class="rounded-full px-2 py-1 text-xs font-semibold" :class="row.type==='in'?'bg-emerald-100 text-emerald-700':'bg-red-100 text-red-700'">{{row.type==='in'?'Kas Masuk':'Kas Keluar'}}</span></td><td>{{row.category}}</td><td><div>{{row.description}}</div><div class="text-xs text-slate-400">{{row.reference_number||'-'}}</div></td><td>{{row.payment_method}}</td><td class="text-right font-semibold" :class="row.type==='in'?'text-emerald-600':'text-red-600'">{{row.type==='in'?'+':'-'}} {{money(row.amount)}}</td></tr><tr v-if="!rows.data.length"><td colspan="7" class="py-12 text-center text-slate-500">Tidak ada transaksi kas sesuai filter.</td></tr></tbody></table></div><div class="flex items-center justify-between border-t p-4"><span class="text-xs text-slate-500">{{rows.from??0}}-{{rows.to??0}} dari {{rows.total}}</span><Pagination :links="rows.links"/></div></section></AuthenticatedLayout></template>
