<!doctype html>
<html lang="id"><head><meta charset="utf-8"><title>Faktur Gabungan - {{ $customer['company_name'] ?: $customer['name'] }}</title>
<style>
@page{size:{{ \App\Support\PrintPaper::cssSize($company) }};margin:{{ \App\Support\PrintPaper::cssMargin($company) }}}*{box-sizing:border-box}body{font-family:Arial,sans-serif;font-size:7px;color:#0f172a;margin:0}.company{text-align:center;border-bottom:2px solid #0ea5e9;padding-bottom:5px}.company h1{font-size:13px;color:#0369a1;margin:0 0 2px}.company p{margin:0}.title{text-align:center;margin:7px 0}.title h2{font-size:12px;margin:0}.customer{border:1px solid #cbd5e1;padding:6px;margin-bottom:7px;line-height:1.5}table{width:100%;border-collapse:collapse}th{background:#0369a1;color:#fff;padding:4px;text-align:left}td{padding:4px;border-bottom:1px solid #e2e8f0}.num{text-align:right}.after{display:table;width:100%;margin-top:7px;table-layout:fixed}.notes,.totals-cell{display:table-cell;vertical-align:top}.notes{width:48%;padding:6px;border:1px solid #cbd5e1;background:#f8fafc;line-height:1.35}.notes h3{margin:0 0 3px;color:#0369a1;font-size:7px}.notes p{margin:0 0 6px}.notes p:last-child{margin-bottom:0}.totals-cell{width:52%;padding-left:8px}.totals{width:100%}.totals td{font-weight:bold}.grand td{border-top:2px solid #0ea5e9;color:#0369a1;font-size:9px}
</style></head><body>
<header class="company"><h1>{{ $company?->company_name ?? 'InvoFlow' }}</h1><p>{{ $company?->address ?: '-' }} | {{ $company?->phone ?: '-' }} | {{ $company?->email ?: '-' }} | NPWP: {{ $company?->tax_number ?: '-' }}</p></header>
<div class="title"><h2>FAKTUR GABUNGAN</h2><strong>Nomor Faktur: {{ $document->facture_number }}</strong><br><span>Tanggal faktur: {{ $document->opened_at->format('d/m/Y') }}</span>@if($document->due_date)<br><strong>Jatuh tempo: {{ $document->due_date->format('d/m/Y') }}</strong>@endif</div>
<section class="customer"><strong>Tagihan Kepada: {{ $customer['company_name'] ?: $customer['name'] }} ({{ $customer['name'] }}) ({{ $customer['phone'] ?: '-' }})</strong><br>Alamat: {{ $customer['address'] ?: '-' }}</section>
<table><thead><tr><th>No</th><th>Nomor Invoice</th><th>No. PO</th><th>Tanggal</th><th class="num">Tagihan</th><th class="num">Terbayar</th><th class="num">Sisa</th></tr></thead><tbody>
@foreach($invoices as $invoice)<tr><td>{{ $loop->iteration }}</td><td>{{ $invoice->invoice_number }}</td><td>{{ $invoice->purchase_order_number ?: '-' }}</td><td>{{ $invoice->invoice_date->format('d/m/Y') }}</td><td class="num">{{ number_format((float)$invoice->grand_total,0,',','.') }}</td><td class="num">{{ number_format((float)$invoice->paid_amount,0,',','.') }}</td><td class="num">{{ number_format((float)$invoice->remaining_amount,0,',','.') }}</td></tr>@endforeach
</tbody></table>
<div class="after">
<section class="notes"><h3>Catatan</h3><p>@forelse($invoices->filter(fn ($invoice) => filled($invoice->notes)) as $invoice)<strong>{{ $invoice->invoice_number }}:</strong> {{ $invoice->notes }}@unless($loop->last)<br>@endunless @empty-@endforelse</p><h3>Syarat pembayaran</h3><p>@if($document->due_date)Pembayaran jatuh tempo tanggal {{ $document->due_date->format('d/m/Y') }}.<br>@endif Pembayaran Melalui Transfer:<br><strong>Bank: {{ $company?->bank_name ?: '-' }} | No Rekening: {{ $company?->bank_account_number ?: '-' }}<br>Atas Nama Rekening: {{ $company?->bank_account_name ?: '-' }}</strong></p></section>
<div class="totals-cell"><table class="totals"><tr><td>Total Tagihan</td><td class="num">Rp {{ number_format((float)$totals['grand_total'],0,',','.') }}</td></tr><tr><td>Total Terbayar</td><td class="num">Rp {{ number_format((float)$totals['paid_total'],0,',','.') }}</td></tr><tr class="grand"><td>TOTAL SISA</td><td class="num">Rp {{ number_format((float)$totals['remaining_total'],0,',','.') }}</td></tr></table></div>
</div>
@if($autoPrint ?? false)<script>window.addEventListener('load',()=>window.setTimeout(()=>window.print(),150));window.addEventListener('afterprint',()=>window.opener?window.close():window.history.back());</script>@endif
</body></html>
